import type { Listing } from "./types";

const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=80`;

/**
 * Demo listings used when Firebase is not configured, or when Firestore has no
 * `listings` documents yet. Keeps the portfolio app fully browsable out of the box.
 */
export const SEED_LISTINGS: Listing[] = [
  {
    id: "seed-malibu-beach-house",
    title: "Oceanfront Modern Beach House",
    description:
      "Wake up to the sound of waves in this light-filled modern home steps from the sand. Floor-to-ceiling windows, a chef's kitchen, and a private deck make this the perfect coastal escape.",
    location: "Malibu, California",
    country: "United States",
    category: "Beachfront",
    pricePerNight: 420,
    rating: 4.97,
    reviewCount: 184,
    guests: 6,
    bedrooms: 3,
    beds: 4,
    baths: 2,
    amenities: ["Wifi", "Kitchen", "Free parking", "Pool", "Ocean view", "Air conditioning"],
    images: [img("1499793983690-e29da59ef1c2"), img("1502672260266-1c1ef2d93688")],
    hostId: "seed-host-1",
    hostName: "Sofia",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
  {
    id: "seed-aspen-cabin",
    title: "Cozy Log Cabin in the Pines",
    description:
      "A handcrafted log cabin tucked into the forest with a wood-burning fireplace, hot tub, and mountain views. Ideal for a quiet weekend off the grid.",
    location: "Aspen, Colorado",
    country: "United States",
    category: "Cabins",
    pricePerNight: 265,
    rating: 4.89,
    reviewCount: 142,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    amenities: ["Wifi", "Kitchen", "Free parking", "Hot tub", "Fireplace", "Mountain view"],
    images: [img("1449158743715-0a90ebb6d2d8"), img("1518780664697-55e3ad937233")],
    hostId: "seed-host-2",
    hostName: "Marcus",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 12,
  },
  {
    id: "seed-nyc-loft",
    title: "Sunlit Loft in SoHo",
    description:
      "Stay in the heart of the city in this industrial-chic loft with exposed brick, high ceilings, and walkable access to the best galleries, shops, and restaurants.",
    location: "New York, New York",
    country: "United States",
    category: "City",
    pricePerNight: 310,
    rating: 4.82,
    reviewCount: 256,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    amenities: ["Wifi", "Kitchen", "Elevator", "Workspace", "Air conditioning"],
    images: [img("1502672260266-1c1ef2d93688"), img("1493809842364-78817add7ffb")],
    hostId: "seed-host-3",
    hostName: "Priya",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: "seed-tuscany-villa",
    title: "Rustic Villa in the Tuscan Hills",
    description:
      "A restored stone villa surrounded by vineyards and olive groves. Enjoy long dinners on the terrace and lazy afternoons by the pool in the Italian countryside.",
    location: "Tuscany",
    country: "Italy",
    category: "Countryside",
    pricePerNight: 380,
    rating: 4.95,
    reviewCount: 98,
    guests: 8,
    bedrooms: 4,
    beds: 5,
    baths: 3,
    amenities: ["Wifi", "Kitchen", "Free parking", "Pool", "Garden", "BBQ grill"],
    images: [img("1512917774080-9991f1c4c750"), img("1564013799919-ab600027ffc6")],
    hostId: "seed-host-4",
    hostName: "Luca",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 20,
  },
  {
    id: "seed-tahoe-lakehouse",
    title: "Lakefront A-Frame Retreat",
    description:
      "Classic A-frame with a private dock right on the water. Kayaks included. Sip coffee on the deck and watch the sun rise over the lake.",
    location: "Lake Tahoe, California",
    country: "United States",
    category: "Lakefront",
    pricePerNight: 295,
    rating: 4.91,
    reviewCount: 167,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 2,
    amenities: ["Wifi", "Kitchen", "Free parking", "Lake access", "Kayak", "Fireplace"],
    images: [img("1503174971373-b1f69850bded"), img("1470770841072-f978cf4d019e")],
    hostId: "seed-host-5",
    hostName: "Hannah",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 8,
  },
  {
    id: "seed-bali-villa",
    title: "Tropical Jungle Villa with Pool",
    description:
      "An open-air villa surrounded by rice paddies and palm trees. Private infinity pool, daily breakfast, and the gentle hum of the jungle all around you.",
    location: "Ubud, Bali",
    country: "Indonesia",
    category: "Tropical",
    pricePerNight: 180,
    rating: 4.98,
    reviewCount: 312,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    amenities: ["Wifi", "Pool", "Breakfast", "Air conditioning", "Garden", "Outdoor shower"],
    images: [img("1537953773345-d172ccf13cf1"), img("1582610116397-edb318620f90")],
    hostId: "seed-host-6",
    hostName: "Wayan",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
  },
  {
    id: "seed-palmsprings-design",
    title: "Mid-Century Modern Desert House",
    description:
      "An architectural gem with clean lines, a saltwater pool, and mountain backdrops. A design lover's dream just minutes from downtown.",
    location: "Palm Springs, California",
    country: "United States",
    category: "Design",
    pricePerNight: 350,
    rating: 4.93,
    reviewCount: 121,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    amenities: ["Wifi", "Kitchen", "Free parking", "Pool", "Air conditioning", "Patio"],
    images: [img("1600585154340-be6161a56a0c"), img("1600566753086-00f18fb6b3ea")],
    hostId: "seed-host-7",
    hostName: "Elena",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 15,
  },
  {
    id: "seed-santorini-luxe",
    title: "Cliffside Luxury Suite with Caldera View",
    description:
      "A whitewashed suite carved into the cliffs with a private plunge pool overlooking the caldera. Watch the world-famous sunset from your own terrace.",
    location: "Santorini",
    country: "Greece",
    category: "Luxe",
    pricePerNight: 640,
    rating: 4.99,
    reviewCount: 203,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ["Wifi", "Plunge pool", "Breakfast", "Air conditioning", "Sea view", "Concierge"],
    images: [img("1570077188670-e3a8d69ac5ff"), img("1469796466635-455ede028aca")],
    hostId: "seed-host-8",
    hostName: "Niko",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
];
